# Disables all modules
cen-all-disable: false

# Use game tick time or system clock time as time measurement?
# For example, when the server's running at 10TPS,
# if below is true, all time options will effectively be doubled.
cen-use-tick-time: true


# Icarus
icarus-enabled: true
# How many durability points to subtract every half-second
# Note that an elytra has 432 total durabilty.
icarus-durability-hit: 10 
icarus-allow-nether: false # Allow elytra in the Nether.
icarus-allow-raining: true # Allow elytra when it is raining (overworld)
icarus-minimum-height: 60 #Minimum Y-height for the effect to kick in.

# Acrophobia
acrophobia-enabled: false
acrophobia-height: 20 #meters over terrain
acrophobia-duration: 5 #seconds
acrophobia-delay: 2 #seconds
acrophobia-power: 1 #power of Blindness effect

# Terminal Velocity
terminal-velocity-enabled: true
terminal-velocity-speed: 10

# Glider
glider-enabled: false

# Limit Boost
limit-boost-enabled: true
limit-boost-time-period: 60 #seconds
limit-boost-count: 2 #fireworks
