# Global disable
cen-all-disable: false

# Use tick time as time measurement?
# When the server's running at 10TPS,
# if below is true, all time options will effectively be doubled.
cen-use-tick-time: true

# Terminal Velocity
terminal-velocity-enabled: true
terminal-velocity-speed: 16

# Glider
glider-enabled: true

# Limit Boost
limit-boost-enabled: true
limit-boost-time-period: 60 #seconds
limit-boost-count: 1 #fireworks

# Fear of Heights
fear-of-heights-enabled: true
fear-of-heights-threshold: 10 #meters over terrain
fear-of-heights-duration: 10 #seconds

# ICARUS
icarus-enabled: true
# How many durability points to subtract every half-second
# Note that an elytra has 432 total durabilty.
icarus-durability-hit: 10 
icarus-allow-nether: false # Allow elytra in the Nether.
icarus-allow-raining: true # Allow elytra when it is raining (overworld)
icarus-minimum-height: 60 #Minimum Y-height for the effect to kick in.
