name: ConfigurableElytraNerfs
version: 1.0.0
main: com.cosmicsubspace.mc.cen.ConfigurableElytraNerfs
description: Nerfs Elytras... configurably.
api-version: '1.17'
commands:
    cen:
        description: Print info about CEN plugin
